"""added relation between application mapping with cloud

Revision ID: 2605a2903ecf
Revises: f29cc8e61d5c
Create Date: 2026-07-14 11:58:58.680121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2605a2903ecf'
down_revision: Union[str, Sequence[str], None] = 'f29cc8e61d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_application_cloud', 'application_cloud_mapping', ['application_id', 'cloud_id'])
    op.create_foreign_key(None, 'application_cloud_mapping', 'application_cloud', ['cloud_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'application_cloud_mapping', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application_cloud_mapping', type_='foreignkey')
    op.drop_constraint(None, 'application_cloud_mapping', type_='foreignkey')
    op.drop_constraint('uq_application_cloud', 'application_cloud_mapping', type_='unique')
    # ### end Alembic commands ###
