"""added application and application cloud mapping model

Revision ID: 4664125a91fd
Revises: ab1ff1e270a1
Create Date: 2026-07-13 14:25:39.842039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4664125a91fd'
down_revision: Union[str, Sequence[str], None] = 'ab1ff1e270a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
