"""added roadmap applicaiton detail tables

Revision ID: 4c12dc9b95c4
Revises: b07a7fecb702
Create Date: 2026-07-24 10:49:30.838782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c12dc9b95c4'
down_revision: Union[str, Sequence[str], None] = 'b07a7fecb702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
