"""added new columns to migration owner remark and security table

Revision ID: 4c719a17f64f
Revises: a88070bad1db
Create Date: 2026-07-15 10:03:36.395980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c719a17f64f'
down_revision: Union[str, Sequence[str], None] = 'a88070bad1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_metadata', sa.Column('assessment_status', sa.String(length=100), nullable=True))
    op.add_column('application_metadata', sa.Column('data_anonymization_status', sa.String(length=100), nullable=True))
    op.add_column('application_migrations', sa.Column('non_production_azure_clusters', sa.String(length=255), nullable=True))
    op.add_column('application_migrations', sa.Column('total_ns', sa.Integer(), nullable=True))
    op.add_column('application_migrations', sa.Column('ns_migration_progress', sa.String(length=100), nullable=True))
    op.add_column('application_migrations', sa.Column('tentative_end_nonprod', sa.Date(), nullable=True))
    op.add_column('application_migrations', sa.Column('tentative_end_prod', sa.Date(), nullable=True))
    op.add_column('application_migrations', sa.Column('ns_backup_creation', sa.String(length=255), nullable=True))
    op.add_column('application_migrations', sa.Column('ns_migration_status', sa.String(length=100), nullable=True))
    op.add_column('application_migrations', sa.Column('cluster', sa.String(length=100), nullable=True))
    op.add_column('application_remarks', sa.Column('remarks_imp', sa.Text(), nullable=True))
    op.add_column('application_remarks', sa.Column('source_comments', sa.Text(), nullable=True))
    op.add_column('application_remarks', sa.Column('archived_remarks', sa.Text(), nullable=True))
    op.add_column('application_security', sa.Column('network_policy_status', sa.String(length=100), nullable=True))
    op.add_column('application_security', sa.Column('security_prod_date', sa.Date(), nullable=True))
    op.add_column('applications', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('confirmed_domain', sa.String(length=150), nullable=True))
    op.add_column('applications', sa.Column('application_status', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('out_of_scope', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'out_of_scope')
    op.drop_column('applications', 'application_status')
    op.drop_column('applications', 'confirmed_domain')
    op.drop_column('applications', 'priority')
    op.drop_column('application_security', 'security_prod_date')
    op.drop_column('application_security', 'network_policy_status')
    op.drop_column('application_remarks', 'archived_remarks')
    op.drop_column('application_remarks', 'source_comments')
    op.drop_column('application_remarks', 'remarks_imp')
    op.drop_column('application_migrations', 'cluster')
    op.drop_column('application_migrations', 'ns_migration_status')
    op.drop_column('application_migrations', 'ns_backup_creation')
    op.drop_column('application_migrations', 'tentative_end_prod')
    op.drop_column('application_migrations', 'tentative_end_nonprod')
    op.drop_column('application_migrations', 'ns_migration_progress')
    op.drop_column('application_migrations', 'total_ns')
    op.drop_column('application_migrations', 'non_production_azure_clusters')
    op.drop_column('application_metadata', 'data_anonymization_status')
    op.drop_column('application_metadata', 'assessment_status')
    # ### end Alembic commands ###
