"""created csv application store models

Revision ID: 920c93c40ab1
Revises: 709151d7c2d9
Create Date: 2026-07-13 09:42:14.199278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920c93c40ab1'
down_revision: Union[str, Sequence[str], None] = '709151d7c2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carto_id', sa.String(length=50), nullable=True),
    sa.Column('application_name', sa.String(length=255), nullable=True),
    sa.Column('basicat', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=150), nullable=True),
    sa.Column('portfolio', sa.String(length=150), nullable=True),
    sa.Column('business_importance', sa.String(length=100), nullable=True),
    sa.Column('sov_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['csv_uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carto_id')
    )
    op.create_table('application_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('dx_uid', sa.String(length=200), nullable=True),
    sa.Column('mcf_id', sa.String(length=200), nullable=True),
    sa.Column('wave', sa.String(length=50), nullable=True),
    sa.Column('gate', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('migration_status', sa.String(length=100), nullable=True),
    sa.Column('migration_progress', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('hosting_location', sa.String(length=100), nullable=True),
    sa.Column('cloud_squad', sa.String(length=100), nullable=True),
    sa.Column('initiated', sa.Date(), nullable=True),
    sa.Column('tentative_start', sa.Date(), nullable=True),
    sa.Column('tentative_end', sa.Date(), nullable=True),
    sa.Column('confirmed_end', sa.Date(), nullable=True),
    sa.Column('go_live', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_remarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('benchmark_status', sa.String(length=50), nullable=True),
    sa.Column('nexus_status', sa.String(length=50), nullable=True),
    sa.Column('rooted_status', sa.String(length=50), nullable=True),
    sa.Column('security_prod_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_security')
    op.drop_table('application_remarks')
    op.drop_table('application_owners')
    op.drop_table('application_migrations')
    op.drop_table('application_metadata')
    op.drop_table('applications')
    # ### end Alembic commands ###
