"""renamed column name from mcf id to mcp id

Revision ID: ab1ff1e270a1
Revises: 920c93c40ab1
Create Date: 2026-07-13 11:38:16.263471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1ff1e270a1'
down_revision: Union[str, Sequence[str], None] = '920c93c40ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_metadata', sa.Column('mcp_id', sa.String(length=200), nullable=True))
    op.drop_column('application_metadata', 'mcf_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_metadata', sa.Column('mcf_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('application_metadata', 'mcp_id')
    # ### end Alembic commands ###
