"""sync csv uploaded files table

Revision ID: b07a7fecb702
Revises: ac0d93568688
Create Date: 2026-07-23 07:16:20.775201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b07a7fecb702'
down_revision: Union[str, Sequence[str], None] = 'ac0d93568688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_application_cloud_mapping'), 'application_cloud_mapping', type_='unique')
    op.add_column('csv_uploaded_files', sa.Column('original_file_name', sa.String(length=255), nullable=True))
    op.add_column('csv_uploaded_files', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('csv_uploaded_files', sa.Column('total_rows', sa.Integer(), nullable=True))
    op.add_column('csv_uploaded_files', sa.Column('processed_rows', sa.Integer(), nullable=True))
    op.add_column('csv_uploaded_files', sa.Column('failed_rows', sa.Integer(), nullable=True))
    op.add_column('csv_uploaded_files', sa.Column('uploaded_by', sa.Integer(), nullable=False))
    op.add_column('csv_uploaded_files', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('csv_uploaded_files', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('csv_uploaded_files', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('csv_uploaded_files', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.create_index(op.f('ix_csv_uploaded_files_id'), 'csv_uploaded_files', ['id'], unique=False)
    op.create_foreign_key(None, 'csv_uploaded_files', 'users', ['uploaded_by'], ['id'])
    op.drop_column('csv_uploaded_files', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csv_uploaded_files', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'csv_uploaded_files', type_='foreignkey')
    op.drop_index(op.f('ix_csv_uploaded_files_id'), table_name='csv_uploaded_files')
    op.alter_column('csv_uploaded_files', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('csv_uploaded_files', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('csv_uploaded_files', 'completed_at')
    op.drop_column('csv_uploaded_files', 'uploaded_at')
    op.drop_column('csv_uploaded_files', 'uploaded_by')
    op.drop_column('csv_uploaded_files', 'failed_rows')
    op.drop_column('csv_uploaded_files', 'processed_rows')
    op.drop_column('csv_uploaded_files', 'total_rows')
    op.drop_column('csv_uploaded_files', 'status')
    op.drop_column('csv_uploaded_files', 'original_file_name')
    op.create_unique_constraint(op.f('uq_application_cloud_mapping'), 'application_cloud_mapping', ['application_id', 'cloud_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
